Update pytest.yaml

diff --git a/.github/workflows/pytest.yaml b/.github/workflows/pytest.yaml
--- a/.github/workflows/pytest.yaml
+++ b/.github/workflows/pytest.yaml
@@ -1,10 +1,6 @@
 name: pytest
 
 on:
-  push:
-    branches:
-      - feat_accelerate_search
-      - accelerate_graph_search_and_getmembers
   pull_request:
   workflow_dispatch:
 
@@ -16,16 +12,6 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v4
 
-      - name: Setup ROS2 sources
-        run: |
-          sudo rm -f /etc/apt/sources.list.d/ros2-latest.list
-          sudo apt update -y
-          sudo apt install curl gnupg2 lsb-release
-          sudo mkdir -p /etc/apt/keyrings
-          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo gpg --dearmor -o /etc/apt/keyrings/ros-archive-keyring.gpg
-          echo "deb [signed-by=/etc/apt/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
-          sudo apt update -y
-
       - name: Install LTTng
         run: |
           sudo apt-get update
@@ -35,16 +21,32 @@ jobs:
           sudo apt-get install -y python3-babeltrace python3-lttng python3-bt2
         shell: bash
 
-      - name: ROSDEP install
+      - name: Set up ROS 2 GPG key
         run: |
-          sudo apt-get install -y python3-rosdep
-          # sudo rosdep init
+          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
+        shell: bash
+
+      - name: Set up ROS 2 repository
+        run: |
+          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
+          sudo apt-get update
+        shell: bash
+
+      - name: Install python3-rosdep
+        run: |
+          sudo apt-get install -y python3-rosdep python3-rosdep-modules
+          sudo rosdep init || echo "rosdep init failed, assuming already initialized"
           rosdep update
-          rosdep install -i --skip-keys "caret_analyze_cpp_impl" --from-paths . -y --rosdistro humble
+        shell: bash
+
+      - name: Run rosdep install
+        run: |
+          rosdep install -y --from-paths src --ignore-src --rosdistro humble
+        shell: bash
+
       - name: Install dependent packages
         run: |
           python3 -m pip install -r src/requirements.txt
-          # cSpell:ignore typeguard
           if dpkg -l | grep -q python3-typeguard; then
             sudo apt remove -y python3-typeguard
           fi
@@ -53,6 +55,7 @@ jobs:
         run: |
           dpkg -l > package_list.txt
           python3 -m pip list > pip_list.txt
+
       - name: Upload package list
         uses: actions/upload-artifact@v4
         with:
@@ -60,9 +63,11 @@ jobs:
           path: |
             package_list.txt
             pip_list.txt
+
       - name: Clone caret_analyze_cpp_impl
         run: |
           git clone https://github.com/tier4/caret_analyze_cpp_impl.git
+
       - name: Restore Cache
         id: cpp_impl-cache
         uses: actions/cache/restore@v4
@@ -100,3 +105,4 @@ jobs:
           echo "Did you send PR to both caret_analyze and caret_analyze_cpp_impl?"
           echo "In that case, this pytest action may fail because it tests new caret_analyze in combination with old caret_analyze_cpp_impl."
           exit 1
+          
